### ISSUE TITLE
Redirect bugs

### ISSUE THREAD

**Issue by SquidDev** [Team-CC-Corp/ClamShell#7]
## Print does not work on multiple arguments when redirected
Creating a file looking like this:
```lua
print("HELLO", "WORLD")
```

then running `file.lua > out.txt; cat out.txt` produces a just the word `HELLO`.

The issue is with [BishInterpreter](https://github.com/ElvishJerricco/ClamShell/blob/master/lib/BishInterpreter.lua#L132). File handles only take one argument.

Either we duplicate the [`stderr.writeLine`](https://github.com/ElvishJerricco/ClamShell/blob/master/lib/BishInterpreter.lua#L30-L33) way of doing things in the `print` function, or override the file handle to accept multiple arguments.

## Stderr is not redirected
I don't know if this is deliberate or not?

**Comment by ElvishJerricco** [comment]
It's stuff like this that makes me really unhappy with the inconsistencies in CraftOS =P

**Comment by SquidDev** [comment]
IKR. Writing my compatibility layer for CC has made me realise how different CC's Lua is from normal Lua. My main issue is that so much could be done with LuaJ but isn't. It works though, So I guess its fine.
